# Generated by Django 4.0.6 on 2022-10-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Writer',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=45)),
                    ],
                    options={
                        'db_table': 'characters_writer',
                    },
                ),

            ],
            database_operations=[],
        )
    ]
