# Generated by Django 4.0.6 on 2022-10-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_season'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Serial',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=85)),
                        ('serial_no', models.PositiveSmallIntegerField()),
                        ('story', models.TextField()),
                        ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season')),
                    ],
                    options={
                        'db_table': 'characters_serial',
                    },
                ),
            ],
            database_operations=[],
        )
    ]
