# Generated by Django 4.0.6 on 2022-10-28 15:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_serial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Actor',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=70)),
                        ('gender', models.CharField(default='male', max_length=6)),
                    ],
                    options={
                        'db_table': 'characters_actor',
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Episode',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=80)),
                        ('episode_type', models.CharField(choices=[('Special', 'Special'), ('Regular', 'Regular')], default='Regular', max_length=7)),
                        ('original_air_date', models.DateField(blank=True, null=True)),
                        ('viewer_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
                        ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.serial')),
                    ],
                    options={
                        'db_table': 'characters_episode',
                    },
                ),
            ],
            database_operations=[],
        ),
        
    ]
