# Generated by Django 4.0.6 on 2022-10-03 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ally',
            options={'verbose_name_plural': 'Allies'},
        ),
    ]
