# Generated by Django 4.0.6 on 2022-10-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_rename_first_name_actor_name_remove_actor_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.serial'),
        ),
    ]
