# Generated by Django 4.0.6 on 2022-10-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_remove_episode_synopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='writer',
        ),
    ]
