# Generated by Django 4.0.6 on 2022-10-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_alter_companion_featured_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='featured_in',
        ),
    ]
