# Generated by Django 4.0.6 on 2022-10-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_alter_companion_featured_in'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ally',
            new_name='AlienRace',
        ),
        migrations.AlterModelOptions(
            name='alienrace',
            options={'verbose_name_plural': 'Alien Races'},
        ),
    ]
