# Generated by Django 4.0.6 on 2022-10-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_alienrace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alienrace',
            name='featured_in',
            field=models.ManyToManyField(to='characters.serial'),
        ),
    ]
