# Generated by Django 4.0.6 on 2022-10-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0027_alienrace_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('nickname', models.CharField(blank=True, max_length=65, null=True)),
                ('image', models.ImageField(upload_to='images/Companions')),
                ('featured_in', models.ManyToManyField(blank=True, to='characters.serial')),
                ('played_by', models.ManyToManyField(to='characters.actor')),
            ],
        ),
    ]
