# Generated by Django 4.0.6 on 2022-10-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0031_rename_episode_type_episode_episode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='story',
            field=models.TextField(),
        ),
    ]
