# Generated by Django 4.0.6 on 2022-10-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0033_alter_alienrace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
