# Generated by Django 4.0.6 on 2022-10-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0034_alter_companion_nickname'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Writer',
                ),
            ],
            # You want to reuse the table, so don't drop it
            database_operations=[],
        )
    ]
