# Generated by Django 4.0.6 on 2022-10-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_serial'),
        ('characters', '0036_alter_doctor_featured_in_alter_serial_season_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='alienrace',
                    name='featured_in',
                    field=models.ManyToManyField(to='api.serial'),
                ),
            ],
            database_operations=[],
        ),
        
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='companion',
                    name='featured_in',
                    field=models.ManyToManyField(blank=True, to='api.serial'),
                ),
            ],
            database_operations=[],
        ),

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='episode',
                    name='serial',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.serial'),
                ),
            ],
            database_operations=[],
        ),
        
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='villain',
                    name='featured_in',
                    field=models.ManyToManyField(blank=True, to='api.serial'),
                ),
            ],
            database_operations=[],
        ),
        
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Serial',
                ),
            ],
            database_operations=[],
        ),
        
    ]
