# Generated by Django 4.0.6 on 2022-10-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_ally_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='nickname',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
