# Generated by Django 4.0.6 on 2022-10-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_writer_episode_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
