# Generated by Django 4.0.6 on 2022-10-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_actor_first_name_remove_actor_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='actor',
            name='last_name',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
