# Generated by Django 4.0.6 on 2022-10-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_rename_name_actor_first_name_actor_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name',
        ),
    ]
