# Generated by Django 4.0.6 on 2022-10-06 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_alter_episode_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='viewer_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
