# Generated by Django 4.0.6 on 2022-10-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_episode_viewer_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='synopsis',
        ),
    ]
