# Generated by Django 4.0.6 on 2022-10-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_alter_companion_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='nickname',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
