# Generated by Django 4.0.6 on 2022-10-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_alter_companion_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='featured_in',
            field=models.ManyToManyField(to='characters.serial'),
        ),
    ]
