# Generated by Django 4.0.6 on 2022-10-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_companion_featured_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
