# Generated by Django 4.0.6 on 2022-10-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_alter_doctor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='featured_in',
            field=models.ManyToManyField(blank=True, to='characters.serial'),
        ),
    ]
