# Generated by Django 4.0.6 on 2022-10-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_rename_ally_alienrace_alter_alienrace_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alienrace',
            name='played_by',
        ),
    ]
