# Generated by Django 4.0.6 on 2022-10-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_remove_alienrace_played_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='alienrace',
            name='image',
            field=models.ImageField(null=True, upload_to='images/Races'),
        ),
    ]
