# Generated by Django 4.0.6 on 2022-10-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0029_villain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='race',
            field=models.ManyToManyField(to='characters.alienrace'),
        ),
        migrations.AddField(
            model_name='villain',
            name='race',
            field=models.ManyToManyField(to='characters.alienrace'),
        ),
    ]
