# Generated by Django 4.0.6 on 2022-10-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0030_companion_race_villain_race'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='Episode_type',
            new_name='episode_type',
        ),
    ]
