# Generated by Django 4.0.6 on 2022-10-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0032_alter_serial_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alienrace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Races'),
        ),
    ]
