# Generated by Django 4.0.6 on 2022-10-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_season'),
        ('characters', '0035_delete_writer'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='doctor',
                    name='featured_in',
                    field=models.ManyToManyField(to='api.season'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='serial',
                    name='season',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season'),
                ),
            ],
            database_operations=[],
        ),
        
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
            name='Season',
                ),
            ],
            database_operations=[],
        )
    ]
